### ISSUE TITLE
doc/feature: add/remove node to cluster

### ISSUE THREAD

**Issue by shaunc** [sagittaros/terraform-k3s-private-cloud#14]
Thank you for this repo! I plan to use this for an "app cluster" in which one service will be running continuously, and another task will run periodically (once daily). I don't want to have to provision a backing node to support the periodic task; rather, I'd like to have a 2nd scaling group that I can scale up when I need it and then scale down. (2nd ASG because different type of node needed. Automatic autoscaling via cluster autoscaler would be even better, but not sure if possible easily outside of EKS.)

Perhaps a "recipe" for this could be added to the doc? Can I just copy the node pool and node code, and use it?

hmm... it seems the `cluster_token` is not part of the outputs. Maybe as well as a recipe, a few changes could be made to enable this?

Alternately, you could support multiple autoscaling groups directly.

**Comment by inscapist** [comment]
Hi @shaunc, I would need some time to recall it, haven't been working on AWS for a year now. 

> Can I just copy the node pool and node code, and use it?

Sure, I don't see why not.

> Alternately, you could support multiple autoscaling groups directly.

The original intention of this project is for independent app clusters, and I am hesitant to complicate it further. As it is, it can be easily forked and customized to suit various needs.

**Comment by shaunc** [comment]
Indeed its simplicity was what attracted me. Ok -- closing. But if I have a simple version of what I want perhaps I'll submit a PR for your consideration. (?)
